// Delegated resumability bootstrap. ScopeRefs resolve from the nearest ancestor so payloads can be shared.
export const RESUMABILITY_BOOTSTRAP = `(()=>{const s=document.currentScript,b=s&&s.src?new URL('../nexil-chunks/',s.src).href:new URL('/nexil-chunks/',document.baseURI).href,p=/^chunk_[a-f0-9]{12}\\.js$/,x=/^[A-Za-z_$][\\w$]*$/,ev='click input change keydown keyup submit focusin focusout'.split(' '),r=globalThis.__nexilScopeRegistry||(globalThis.__nexilScopeRegistry=new Map),q=v=>{const c=new Set,f=()=>v;Object.defineProperty(f,'value',{enumerable:!0,get:()=>v});f.set=n=>{n=typeof n==='function'?n(v):n;if(Object.is(v,n))return;v=n;for(const l of[...c])l()};f.subscribe=l=>(c.add(l),()=>c.delete(l));return f},o=e=>{while(e&&e!==document&&!e.hasAttribute('data-nx-scope'))e=e.parentElement;return e},w=e=>{e=o(e);if(!e)return{};const a=e.getAttribute('data-nx-scope');let z;try{z=JSON.parse(a)}catch{return{}}const out={};for(const[n,t]of Object.entries(z||{})){if(t.kind==='value')out[n]=t.data;else if(t.kind==='unsupported')console.warn('[nexil] unsupported scope:',t.reason);else{let v=r.get(t.id);if(!v){if(t.kind==='signal')v=q(t.initial);else if(t.kind==='store'){const qv=q(t.initial);v={value:qv,snapshot:()=>qv(),set:n=>qv.set(n)}}else if(t.kind==='action')v=n=>fetch(t.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(n)}).then(e=>e.json());v&&r.set(t.id,v)}v&&(out[n]=v)}}return out},d=(e,t,n)=>{const i=n.indexOf('#');if(i<1)return;const c=n.slice(0,i),o=n.slice(i+1);if(!p.test(c)||!x.test(o))return;import(b+c).then(m=>m[o]?.({element:e,event:t,scope:w(e)})).catch(e=>console.warn('[nexil] handler failed',e))},g=t=>{if(t.type==='submit')t.preventDefault();for(let e=t.target;e&&e!==document;e=e.parentElement){const n=e.getAttribute('data-nx-on-'+t.type);n&&n.split(';').forEach(n=>d(e,t,n))}};ev.forEach(e=>document.addEventListener(e,g))})();
`

// Scalar Signal-to-DOM bindings are isolated so the resumability bootstrap keeps
// its existing budget. It is loaded only when a route contains data-nx-bind.
export const RESUMABILITY_FORMS = `(()=>{const f=e=>{const o={};new FormData(e).forEach((v,k)=>{const p=o[k];o[k]=p===undefined?v:Array.isArray(p)?[...p,v]:[p,v]});return o},h=e=>{const t=e.target.closest?.('form[data-nx-form]');if(!t||t.hasAttribute('data-nx-on-submit'))return;e.preventDefault();const b=t.querySelector('[data-nx-submit-button]'),l=b?.getAttribute('data-nx-loading-text'),old=b?.textContent,k=globalThis.crypto?.randomUUID?.()||'nx-'+Date.now().toString(36);if(b){b.disabled=!0;if(l)b.textContent=l}t.setAttribute('aria-busy','true');fetch(t.getAttribute('action')||t.action,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':k,...(t.getAttribute('data-nx-csrf')?{'X-CSRF-Token':t.getAttribute('data-nx-csrf')}: {})},body:JSON.stringify(f(t))}).then(async r=>{const d=await r.json().catch(()=>({ok:!1,errors:['Invalid action response.']}));t.dispatchEvent(new CustomEvent(r.ok?'nexil:form-success':'nexil:form-error',{detail:d.ok?d.data:d.errors}));return d}).finally(()=>{t.removeAttribute('aria-busy');if(b){b.disabled=!1;b.textContent=old||''}})};document.addEventListener('submit',h)})();\n`

// Scalar Signal-to-DOM bindings are isolated so the resumability bootstrap keeps
// its existing budget. It is loaded only when a route contains data-nx-bind.
export const RESUMABILITY_BINDINGS = `(()=>{const i=/^nx:(?:signal|store):[A-Za-z0-9_-]+$/,r=globalThis.__nexilScopeRegistry||(globalThis.__nexilScopeRegistry=new Map),c=[],q=v=>{const s=new Set,f=()=>v;f.set=n=>{n=typeof n==='function'?n(v):n;if(Object.is(v,n))return;v=n;for(const l of[...s])l()};f.subscribe=l=>(s.add(l),()=>s.delete(l));return f},o=e=>{while(e&&e!==document&&!e.hasAttribute('data-nx-scope'))e=e.parentElement;return e},w=e=>{e=o(e);if(!e)return{};let a=e.getAttribute('data-nx-scope'),z;try{z=JSON.parse(a)}catch{return{}}const out={};for(const[n,t]of Object.entries(z||{})){if(t.kind==='signal'){let v=r.get(t.id);if(!v)r.set(t.id,v=q(t.initial));out[n]=r.get(t.id)}else if(t.kind==='store'){let v=r.get(t.id);if(!v){const qv=q(t.initial);v={value:qv};r.set(t.id,v)}out[n]=r.get(t.id)}}return out},m=(e,id)=>{const z=w(e);for(const n in z){const v=z[n];if(v&&v.value&&typeof v.value.subscribe==='function'){if(v.value===r.get(id)?.value)return v.value}else if(v===r.get(id))return v}},y=(e,k,v)=>{if(k==='text')e.textContent=v==null?'':String(v);else if(k==='value')e.value=v==null?'':String(v);else if(k==='checked')e.checked=!!v;else if(k==='disabled')e.disabled=!!v;else if(k==='hidden')e.hidden=!!v;else if(k==='class')e.className=v==null?'':String(v);else if(k==='style'){if(v&&typeof v==='object')Object.assign(e.style,v);else e.style.cssText=v==null?'':String(v)}else if(k==='href'||k==='src'){if(v==null||v==='')e.removeAttribute(k);else e.setAttribute(k,String(v))}else if(k.startsWith('aria-')){if(v==null)e.removeAttribute(k);else e.setAttribute(k,String(v))}},h=()=>{for(const e of document.querySelectorAll('[data-nx-bind]')){const a=e.getAttribute('data-nx-bind');for(const t of(a||'').split(';')){const n=t.lastIndexOf('#'),id=t.slice(0,n),k=t.slice(n+1),v=m(e,id);if(n<1||!i.test(id)||(!['text','value','checked','disabled','hidden','class','style','href','src'].includes(k)&&!/^aria-[a-z][a-z0-9-]*$/.test(k))||typeof v!=='function'||typeof v.subscribe!=='function')continue;const f=()=>y(e,k,v());f();c.push(v.subscribe(f))}}};globalThis.__nexilDisposeBindings=()=>{c.splice(0).forEach(e=>e());r.clear()};h()})();
`
