/**
 * Production-only resumability runtime for opaque data-nx-scope keys.
 * Its generated state asset exposes the browser-required payload through
 * globalThis.__nexilScopeSeeds; state stays public browser data, but does not
 * bloat or reveal named values in the HTML document itself.
 */
export const RESUMABILITY_BOOTSTRAP_EXTERNAL = `(()=>{
	const script=document.currentScript,chunkBase=script&&script.src?new URL('../nexil-chunks/',script.src).href:new URL('/nexil-chunks/',document.baseURI).href,chunk=/^chunk_[a-f0-9]{12}\\.js$/,exportName=/^[A-Za-z_$][\\w$]*$/,events='click input change keydown keyup submit focusin focusout'.split(' '),registry=globalThis.__nexilScopeRegistry||(globalThis.__nexilScopeRegistry=new Map);
	const signal=initial=>{const listeners=new Set,read=()=>initial;Object.defineProperty(read,'value',{enumerable:true,get:()=>initial});read.set=next=>{next=typeof next==='function'?next(initial):next;if(Object.is(initial,next))return;initial=next;for(const l of[...listeners])l()};read.subscribe=listener=>(listeners.add(listener),()=>listeners.delete(listener));return read};
	const payloads=element=>{const stack=[];for(let cur=element;cur&&cur!==document;cur=cur.parentElement)if(cur.hasAttribute('data-nx-scope')){try{const raw=cur.getAttribute('data-nx-scope');const z=raw.startsWith('nx:scope:')?globalThis.__nexilScopeSeeds?.[raw]||{}:JSON.parse(raw);stack.push(z)}catch{}}const out={};for(let i=stack.length-1;i>=0;i--)for(const k in stack[i])if(out[k]===undefined)out[k]=stack[i][k];return out};
	const scope=element=>{const resolved={};for(const[name,ref]of Object.entries(payloads(element))){if(ref.kind==='value')resolved[name]=ref.data;else if(ref.kind==='unsupported')console.warn('[nexil]',ref.reason);else if(ref.kind==='ctx'){let live=registry.get(ref.id);if(!live){live={value:ref.initial,use:()=>registry.get(ref.id).value,useContext:()=>registry.get(ref.id).value,g:ref.lifetime==='global'};registry.set(ref.id,live)}else if(ref.lifetime==='global'&&!live.g)live.g=true;live=registry.get(ref.id);resolved[name]=/Context$/.test(name)?live:live.value;continue}else{let live=registry.get(ref.id);if(!live){if(ref.kind==='signal')live=signal(ref.initial);else if(ref.kind==='store'){const value=signal(ref.initial);live={value,snapshot:()=>value(),set:next=>value.set(next),g:ref.lifetime==='global'}}else if(ref.kind==='action')live=input=>fetch(ref.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}).then(response=>response.json());if(live)registry.set(ref.id,live)}else if(ref.lifetime==='global'&&live&&!live.g)live.g=true;if(live)resolved[name]=live}}return resolved};
	const invoke=(element,event,reference)=>{const marker=reference.indexOf('#');if(marker<1)return;const file=reference.slice(0,marker),name=reference.slice(marker+1);if(!chunk.test(file)||!exportName.test(name))return;import(chunkBase+file).then(module=>module[name]?.({element,event,scope:scope(element)})).catch(error=>console.warn('[nexil] handler failed',error))};
	const dispatch=event=>{if(event.type==='submit')event.preventDefault();for(let element=event.target;element&&element!==document;element=element.parentElement){const refs=element.getAttribute('data-nx-on-'+event.type);if(refs)refs.split(';').forEach(reference=>invoke(element,event,reference))}};
	events.forEach(event=>document.addEventListener(event,dispatch));
	})();\n`
